# Generated by Django 4.2.2 on 2023-10-08 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateb', models.DateTimeField(verbose_name='dateb')),
                ('client', models.CharField(blank=True, max_length=256, null=True, verbose_name='client_name')),
                ('place', models.CharField(max_length=32, verbose_name='place')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='total')),
                ('discount', models.IntegerField(default=0, verbose_name='discount')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='bonus')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='amount')),
                ('detailing', models.TextField(blank=True, null=True, verbose_name='bill_details')),
            ],
            options={
                'db_table': 'view_bill',
                'ordering': ['dateb'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='category_id')),
                ('category', models.CharField(max_length=128, verbose_name='category_title')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo')),
            ],
            options={
                'db_table': 'view_catalog',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewDetailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.IntegerField(verbose_name='bill_id')),
                ('dateb', models.DateTimeField(verbose_name='dateb')),
                ('client_id', models.IntegerField(verbose_name='client_id')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='client_name')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='client_email')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='client_phone')),
                ('place', models.CharField(max_length=32, verbose_name='place')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='total')),
                ('discount', models.IntegerField(default=0, verbose_name='discount')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='bonus')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='amount')),
                ('catalog_id', models.IntegerField(verbose_name='catalog_id')),
                ('category', models.CharField(max_length=128, verbose_name='category_title')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('detailing_total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='detailing_total')),
            ],
            options={
                'db_table': 'view_detailing',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketday', models.DateTimeField(auto_now_add=True, verbose_name='basketday')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
            ],
            options={
                'db_table': 'basket',
                'ordering': ['basketday'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateb', models.DateTimeField(auto_now_add=True, verbose_name='dateb')),
                ('place', models.CharField(max_length=32, verbose_name='place')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='total')),
                ('discount', models.IntegerField(default=0, verbose_name='discount')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='bonus')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='amount')),
            ],
            options={
                'db_table': 'bill',
                'ordering': ['dateb'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo')),
            ],
            options={
                'db_table': 'catalog',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='category_title')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, verbose_name='client_email')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=128, verbose_name='client_name')),
                ('phone', models.CharField(max_length=32, verbose_name='client_phone')),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
            ],
            options={
                'db_table': 'client',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dater', models.DateTimeField(auto_now_add=True, verbose_name='dater')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('details', models.TextField(verbose_name='review_details')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_client', to='star.client')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['dater'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.DateTimeField(verbose_name='daten')),
                ('title', models.CharField(max_length=256, verbose_name='title_news')),
                ('details', models.TextField(verbose_name='details_news')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo_news')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['daten'],
                'indexes': [models.Index(fields=['daten'], name='news_daten_a29edb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Detailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailing_bill', to='star.bill')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailing_catalog', to='star.catalog')),
            ],
            options={
                'db_table': 'detailing',
                'ordering': ['bill'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='client_email_1d3242_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='client_name_57da18_idx'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_category', to='star.category'),
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_client', to='star.client'),
        ),
        migrations.AddField(
            model_name='basket',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_catalog', to='star.catalog'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_basket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['dater'], name='review_dater_4d3a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='detailing',
            index=models.Index(fields=['bill'], name='detailing_bill_id_362dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='detailing',
            index=models.Index(fields=['catalog'], name='detailing_catalog_e77725_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['title'], name='catalog_title_a1bae3_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['dateb'], name='bill_dateb_2ea0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['basketday'], name='basket_basketd_d70b82_idx'),
        ),
    ]
